spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres:5433/order_service_db
spring.datasource.username=order_user
spring.datasource.password=order_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true

spring.cache.type=simple
spring.cache.cache-names=orders,ordersByNumber

catalog.service.url=http://book-catalog-service:8081
user.service.url=http://user-service:8083

logging.level.com.otus.order_service=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.cache=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.db.enabled=true
