GET http://localhost:8082/api/orders/1

POST http://localhost:8082/api/orders
Content-Type: application/json

{
  "userId": 1,
  "shippingAddress": "г. Москва, ул. Вавилова, д. 12, кв. 45",
  "paymentMethod": "CREDIT_CARD",
  "items": [
    {
      "bookId": 1,
      "quantity": 3
    }
  ]
}

GET http://user.local:8080/api/users/1

POST http://localhost:32290/api/users/login
Content-Type: application/json
{
  "usernameOrEmail": "Aelex",
  "password": "612536fgfgh"
}

GET http://localhost:32290/actuator/health
