spring.application.name=book-catalog-service
server.port=8082

spring.datasource.url=jdbc:postgresql://order-db:5432/order_db
spring.datasource.username=order_user
spring.datasource.password=order_password

catalog.service.url=http://book-catalog-service:8081
user.service.url=http://user-service:8083

spring.jpa.hibernate.ddl-auto=update
