spring.application.name=book-catalog-service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/book_catalog_db
spring.datasource.username=catalog_user
spring.datasource.password=catalog_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
logging.level.org.hibernate=WARN
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

spring.cache.type=simple
spring.cache.cache-names=books,categories

logging.level.com.otus.book_catalog_service=INFO
logging.level.org.springframework.cache=WARN
logging.level.org.hibernate.SQL=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.io.github.resilience4j=INFO
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j.ratelimiter=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true

# ==============================
# RESILIENCE4J CIRCUIT BREAKER
# ==============================

resilience4j.circuitbreaker.configs.default.sliding-window-type=count_based
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.slow-call-duration-threshold=2s
resilience4j.circuitbreaker.configs.default.slow-call-rate-threshold=50
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true


resilience4j.circuitbreaker.instances.catalogService.sliding-window-size=20
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.catalogService.minimum-number-of-calls=10

# ==========================
# RESILIENCE4J RATE LIMITER
# ==========================

resilience4j.ratelimiter.configs.default.limit-for-period=10
resilience4j.ratelimiter.configs.default.limit-refresh-period=1s
resilience4j.ratelimiter.configs.default.timeout-duration=500ms
resilience4j.ratelimiter.configs.default.allow-healthy-only=true


resilience4j.ratelimiter.instances.catalogService.limit-for-period=5
resilience4j.ratelimiter.instances.catalogService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.catalogService.timeout-duration=1s

# ===================
# RESILIENCE4J RETRY
# ===================

resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.wait-duration=1s
resilience4j.retry.configs.default.exponential-backoff-multiplier=2
resilience4j.retry.configs.default.max-wait-duration=5s

resilience4j.retry.instances.catalogService.max-attempts=2
resilience4j.retry.instances.catalogService.wait-duration=2s