spring.application.name=book-catalog-service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/book_catalog_db
spring.datasource.username=catalog_user
spring.datasource.password=catalog_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
logging.level.org.hibernate=WARN
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

spring.cache.type=simple
spring.cache.cache-names=books,categories

logging.level.com.otus.book_catalog_service=INFO
logging.level.org.springframework.cache=WARN
logging.level.org.hibernate.SQL=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n